# Generated by Django 4.2.7 on 2026-04-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_patient_prediction_user_alter_patientrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code', max_length=20, null=True),
        ),
    ]
